title: DreamSpa VR
description: A virtual reality, kaleidoscope based meditative experience. Almost feels like a dream.
show_downloads: true
google_analytics:
theme: jekyll-theme-time-machine
markdown: kramdown
